domain: https://djtakushi.github.io/dblog/       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#baseurl: /dblog
url: https://djtakushi.github.io/dblog/
#permalink: /:title     #this actually works now, it didn't for me last time, not sure wh


#domain: my-site.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#url: https://my-site.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder


collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

#baseurl: "/dblog"
#url: "djtakushi.github.io/dblog"
#permalink: /:title
